name: Cross-Platform

on:
  push:
    tags:
      - "v*.*.*"
  pull_request:
    paths-ignore:
      - README.md
      - LICENSE
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

# only run most recent workflow in branch
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  # armv7:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #       with:
  #         platforms: linux/arm/v7
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: build
  #       run: docker buildx build --platform linux/arm/v7 -t armv7 .
  amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup build environment
        run: docker build -t amd64 .
      - name: Build
        run: |
          chmod +x scripts/dockerConfigureBuild.sh
          docker run --rm \
            -v $(realpath .):/src \
            -e SYSINFO_SRC=/src \
            -e SYSINFO_BUILD=/src/build \
            amd64 \
            /src/scripts/dockerConfigureBuild.sh
      - name: Prepare artifacts
        run: |
          mv -v build/sysinfo build/sysinfo-amd64
      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/sysinfo-*
  arm64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/arm64
      - name: Setup build environment
        run: docker buildx build --platform linux/arm64 -t arm64 .
      - name: Build
        run: |
          chmod +x scripts/dockerConfigureBuild.sh
          docker run --platform linux/arm64 --rm \
            -v $(realpath .):/src \
            -e SYSINFO_SRC=/src \
            -e SYSINFO_BUILD=/src/build \
            arm64 \
            /src/scripts/dockerConfigureBuild.sh
      - name: Prepare artifacts
        run: |
          mv -v build/sysinfo build/sysinfo-arm64
      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/sysinfo-*
  ppc64le:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: linux/ppc64le
      - name: Setup build environment
        run: docker buildx build --platform linux/ppc64le -f ppc64le.dockerfile -t ppc64le .
      - name: Build
        run: |
          chmod +x scripts/dockerConfigureBuild.sh
          docker run --platform linux/ppc64le --rm \
            -v $(realpath .):/src \
            -e SYSINFO_SRC=/src \
            -e SYSINFO_BUILD=/src/build \
            ppc64le \
            /src/scripts/dockerConfigureBuild.sh
      - name: Prepare artifacts
        run: |
          mv -v build/sysinfo build/sysinfo-ppc64le
      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/sysinfo-*