name: Cross-Platform

on:
  push:
    branches: [ "master" ]
    tags:
      - "v*.*.*"
  pull_request:
    branches: [ "master" ]
  workflow_dispatch:

permissions:
  contents: write

jobs:
  # arm64:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #       with:
  #         platforms: linux/arm64
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Setup build environment
  #       run: docker buildx build --platform linux/arm64 -t arm64 .
  #     - name: Build
  #       run: mkdir -p build \
  #         docker run --rm \
  #         -v $(realpath .):/src \
  #         -e SYSINFO_SRC=/src,SYSINFO_BUILD=/src/build \
  #         /src/build/configureBuild.sh
  # armv7:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #       with:
  #         platforms: linux/arm/v7
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: build
  #       run: docker buildx build --platform linux/arm/v7 -t armv7 .
  # ppc64le:
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #       with:
  #         platforms: linux/ppc64le
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: build
  #       run: docker buildx build --platform linux/ppc64le -t ppc64le .
  amd64:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup build environment
        run: docker build -t amd64 .
      - name: Build
        run: |
          chmod +x scripts/dockerConfigureBuild.sh  
          docker run --rm \
            -v $(realpath .):/src \
            -e SYSINFO_SRC=/src \
            -e SYSINFO_BUILD=/src/build \
            amd64 \
            /src/scripts/dockerConfigureBuild.sh
      - name: Prepare artifacts
        run: |
          mv -v build/sysinfo build/sysinfo-amd64
      - name: Upload artifacts
        if: startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: build/sysinfo-*